/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DOAssetController;
import controller.DOSettlementController;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.DOSettlementModel;
import view.form.Form_DeliveryOrders;
import view.main.Home;

/**
 *
 * @author dandy
 */
public class Frame_DetailDeliveryOrder extends javax.swing.JFrame {

    
    Form_DeliveryOrders formDeliveryOrders;
    DOAssetController doAssetController;
    Frame_AddDOAsset addDOAssetView;
    Frame_CreateSettlement createSettlementView;
    Home home;
    
    /**
     * Creates new form JFCreateUser
     */
    public Frame_DetailDeliveryOrder(Form_DeliveryOrders formDeliveryOrders, Home home) {
        this.formDeliveryOrders = formDeliveryOrders;
        this.home = home;
        initComponents();
        
        jLabelId.setVisible(false);
    }
    
    public JTable getDataTable() {
        return getjTableDOAssets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPhone = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextTicketDescription = new javax.swing.JTextArea();
        jLabelTicketId = new javax.swing.JLabel();
        jLabelTeamWH = new javax.swing.JLabel();
        jButtonAddAsset = new javax.swing.JButton();
        jButtonDeleteAsset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDOAssets = new javax.swing.JTable();
        jTextTicketId = new javax.swing.JTextField();
        jTextProblem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextTicketStatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelDescription1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextCustomerDescription = new javax.swing.JTextArea();
        jTextTeamWarehouse = new javax.swing.JTextField();
        jTextTeamEngineer = new javax.swing.JTextField();
        jButtonSettleAsset = new javax.swing.JButton();
        jTextCustomerName = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonPrintDO = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();

        jLabelPhone.setText("jLabel5");

        jLabelAddress.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 148, 251), 10));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setText("Detail Delivery Order");

        jLabelDescription.setText("Ticket Desc");

        jTextTicketDescription.setEditable(false);
        jTextTicketDescription.setColumns(20);
        jTextTicketDescription.setRows(5);
        jScrollPane1.setViewportView(jTextTicketDescription);

        jLabelTicketId.setText("Ticket ID");

        jLabelTeamWH.setText("Problem");

        jButtonAddAsset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/add.png"))); // NOI18N
        jButtonAddAsset.setText("Add Asset");
        jButtonAddAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAssetActionPerformed(evt);
            }
        });

        jButtonDeleteAsset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/delete.png"))); // NOI18N
        jButtonDeleteAsset.setText("Delete Asset");
        jButtonDeleteAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAssetActionPerformed(evt);
            }
        });

        jTableDOAssets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Asset ID", "Brand/Category", "Name", "Model/PN", "Serial Number", "Qty"
            }
        ));
        jScrollPane2.setViewportView(jTableDOAssets);

        jTextTicketId.setEditable(false);

        jTextProblem.setEditable(false);

        jLabel1.setText("Ticket Status");

        jTextTicketStatus.setEditable(false);

        jLabel2.setText("PIC Warehouse");

        jLabel3.setText("PIC Engineer");

        jLabel4.setText("PIC Customer");

        jLabelDescription1.setText("Customer Desc");

        jTextCustomerDescription.setEditable(false);
        jTextCustomerDescription.setColumns(20);
        jTextCustomerDescription.setRows(5);
        jScrollPane3.setViewportView(jTextCustomerDescription);

        jTextTeamWarehouse.setEditable(false);

        jTextTeamEngineer.setEditable(false);

        jButtonSettleAsset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/folder_go.png"))); // NOI18N
        jButtonSettleAsset.setText("Settle Asset");
        jButtonSettleAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettleAssetActionPerformed(evt);
            }
        });

        jTextCustomerName.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddAsset)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteAsset)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSettleAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTicketId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTeamWH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextTicketStatus)
                            .addComponent(jTextTicketId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextProblem, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextTeamWarehouse))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextTeamEngineer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextCustomerName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3)))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTicketStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTeamWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextTeamEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextTicketId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTicketId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTeamWH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextProblem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddAsset)
                            .addComponent(jButtonDeleteAsset)
                            .addComponent(jButtonSettleAsset)))
                    .addComponent(jLabelDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cancel.png"))); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonPrintDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/printer.png"))); // NOI18N
        jButtonPrintDO.setText("Print DO");
        jButtonPrintDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintDOActionPerformed(evt);
            }
        });

        jLabelId.setText("jLabelId");

        jDesktopPane1.setLayer(jLabelTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonPrintDO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelId, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelId))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jButtonPrintDO, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelId)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonPrintDO))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrintDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintDOActionPerformed
        JFileChooser chooser = new JFileChooser("");
        int r = chooser.showSaveDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            String dir = chooser.getSelectedFile().getAbsolutePath();
            doAssetController = new DOAssetController(this);
            doAssetController.printDO(this, dir);
        }
    }//GEN-LAST:event_jButtonPrintDOActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAddAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAssetActionPerformed
        addDOAssetView = new Frame_AddDOAsset(this, home);
        addDOAssetView.getjLabelId().setText(getjLabelId().getText());
        addDOAssetView.pack();
        addDOAssetView.setLocationRelativeTo(null);
        addDOAssetView.setVisible(true);
        addDOAssetView.setAlwaysOnTop(true);
    }//GEN-LAST:event_jButtonAddAssetActionPerformed

    private void jButtonDeleteAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAssetActionPerformed
        if (jTableDOAssets.getSelectedRow() >= 0){
            int dialogResult = JOptionPane.showConfirmDialog (this, "Do you want to delete this asset in DO?","INFO",JOptionPane.WARNING_MESSAGE);
            if(dialogResult == JOptionPane.YES_OPTION){
                doAssetController = new DOAssetController(this);
                String id = jTableDOAssets.getValueAt(jTableDOAssets.getSelectedRow(),0).toString();
                int assetId = Integer.parseInt(jTableDOAssets.getValueAt(jTableDOAssets.getSelectedRow(),1).toString());
                int qty = Integer.parseInt(jTableDOAssets.getValueAt(jTableDOAssets.getSelectedRow(),9).toString());
                doAssetController.deleteDOAsset(id, assetId, qty, this);
                int doId = Integer.parseInt(getjLabelId().getText());
                doAssetController.showDOAssets(doId);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select one data to delete!","WARNING",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteAssetActionPerformed

    private void jButtonSettleAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettleAssetActionPerformed
        // TODO add your handling code here:
        int doId = Integer.parseInt(getjLabelId().getText());
        if (jTableDOAssets.getSelectedRow() >= 0){
            doAssetController = new DOAssetController(this);
            String id = jTableDOAssets.getValueAt(jTableDOAssets.getSelectedRow(),0).toString();
            String assetId = jTableDOAssets.getValueAt(jTableDOAssets.getSelectedRow(),1).toString();
            String model = jTableDOAssets.getValueAt(jTableDOAssets.getSelectedRow(),5).toString();
            String serialNumber = jTableDOAssets.getValueAt(jTableDOAssets.getSelectedRow(),7).toString();
            String name = jTableDOAssets.getValueAt(jTableDOAssets.getSelectedRow(),4).toString();
            String qty = jTableDOAssets.getValueAt(jTableDOAssets.getSelectedRow(),9).toString();
            if(doAssetController.getDOSettlementByDOAssetId(Integer.parseInt(id)) != -1) {
                int doSettlementId = doAssetController.getDOSettlementByDOAssetId(Integer.parseInt(id));
                createSettlementView = new Frame_CreateSettlement(this, home, doId);
                createSettlementView.pack();
                createSettlementView.setLocationRelativeTo(null);
                createSettlementView.getjLabelTitle().setText("Edit Asset Settlement");
                createSettlementView.getjButtonSave().setText("Update");
                createSettlementView.setVisible(true);
                createSettlementView.setAlwaysOnTop(true);
                createSettlementView.getjLabelId().setText(Integer.toString(doSettlementId));
                createSettlementView.getjTextDOAssetId().setText(id + " | " + assetId);
                createSettlementView.getjTextModelNumber().setText(model);
                createSettlementView.getjTextSerialNumber().setText(serialNumber);
                createSettlementView.getjTextName().setText(name);
                createSettlementView.getjTextQty().setText(qty);
                createSettlementView.getjLabelDOQty().setText(qty);
                
                // get data
                DOSettlementController doSettlementController = new DOSettlementController();
                DOSettlementModel doSettlement = doSettlementController.getSettlementById(doSettlementId);
                createSettlementView.getjTextFaultyName().setText(doSettlement.getFaultName());
                createSettlementView.getjTextFaultyModel().setText(doSettlement.getFaultModelNumber());
                createSettlementView.getjTextFaultySerialNumber().setText(doSettlement.getFaultSerialNumber());
                createSettlementView.getjTextFaultyQty().setText(Integer.toString(doSettlement.getFaultQty()));
                createSettlementView.getjTextNotes().setText(doSettlement.getNotes());
            } else {
                createSettlementView = new Frame_CreateSettlement(this, home, doId);
                createSettlementView.pack();
                createSettlementView.setLocationRelativeTo(null);
                createSettlementView.setVisible(true);
                createSettlementView.setAlwaysOnTop(true);
                createSettlementView.getjTextDOAssetId().setText(id + " | " + assetId);
                createSettlementView.getjTextModelNumber().setText(model);
                createSettlementView.getjTextSerialNumber().setText(serialNumber);
                createSettlementView.getjTextName().setText(name);
                createSettlementView.getjTextQty().setText(qty);
                createSettlementView.getjLabelDOQty().setText(qty);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select one data to create replacement!","WARNING",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSettleAssetActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFCreateUser().setVisible(true);
//            }
//        });
//    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAsset;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDeleteAsset;
    private javax.swing.JButton jButtonPrintDO;
    private javax.swing.JButton jButtonSettleAsset;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelDescription1;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelTeamWH;
    private javax.swing.JLabel jLabelTicketId;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDOAssets;
    private javax.swing.JTextArea jTextCustomerDescription;
    private javax.swing.JTextField jTextCustomerName;
    private javax.swing.JTextField jTextProblem;
    private javax.swing.JTextField jTextTeamEngineer;
    private javax.swing.JTextField jTextTeamWarehouse;
    private javax.swing.JTextArea jTextTicketDescription;
    private javax.swing.JTextField jTextTicketId;
    private javax.swing.JTextField jTextTicketStatus;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jButtonAddAsset
     */
    public javax.swing.JButton getjButtonAddAsset() {
        return jButtonAddAsset;
    }

    /**
     * @return the jButtonCancel
     */
    public javax.swing.JButton getjButtonCancel() {
        return jButtonCancel;
    }

    /**
     * @return the jButtonDeleteAsset
     */
    public javax.swing.JButton getjButtonDeleteAsset() {
        return jButtonDeleteAsset;
    }

    /**
     * @return the jButtonPrintDO
     */
    public javax.swing.JButton getjButtonPrintDO() {
        return jButtonPrintDO;
    }

    /**
     * @return the jTableDOAssets
     */
    public javax.swing.JTable getjTableDOAssets() {
        return jTableDOAssets;
    }

    /**
     * @return the jTextCustomerName
     */
    public javax.swing.JTextField getjTextCustomerName() {
        return jTextCustomerName;
    }

    /**
     * @return the jTextCustomerDescription
     */
    public javax.swing.JTextArea getjTextCustomerDescription() {
        return jTextCustomerDescription;
    }

    /**
     * @return the jTextTicketDescription
     */
    public javax.swing.JTextArea getjTextTicketDescription() {
        return jTextTicketDescription;
    }

    /**
     * @return the jTextProblem
     */
    public javax.swing.JTextField getjTextProblem() {
        return jTextProblem;
    }

    /**
     * @return the jTextTeamEngineer
     */
    public javax.swing.JTextField getjTextTeamEngineer() {
        return jTextTeamEngineer;
    }

    /**
     * @return the jTextTeamWarehouse
     */
    public javax.swing.JTextField getjTextTeamWarehouse() {
        return jTextTeamWarehouse;
    }

    /**
     * @return the jTextTicketId
     */
    public javax.swing.JTextField getjTextTicketId() {
        return jTextTicketId;
    }

    /**
     * @return the jTextTicketStatus
     */
    public javax.swing.JTextField getjTextTicketStatus() {
        return jTextTicketStatus;
    }

    /**
     * @return the jLabelId
     */
    public javax.swing.JLabel getjLabelId() {
        return jLabelId;
    }
    
    public void hideIdColumn() {
        // Gunakan nama variabel yang berbeda untuk jTableDOAssets
        JTable table = getDataTable();

        // Sembunyikan kolom ID (kolom pertama)
        table.getColumnModel().getColumn(0).setMinWidth(0);
        table.getColumnModel().getColumn(0).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setWidth(0);
        table.getColumnModel().getColumn(3).setMinWidth(0);
        table.getColumnModel().getColumn(3).setMaxWidth(0);
        table.getColumnModel().getColumn(3).setWidth(0);
        table.getColumnModel().getColumn(6).setMinWidth(0);
        table.getColumnModel().getColumn(6).setMaxWidth(0);
        table.getColumnModel().getColumn(6).setWidth(0);
        table.getColumnModel().getColumn(8).setMinWidth(0);
        table.getColumnModel().getColumn(8).setMaxWidth(0);
        table.getColumnModel().getColumn(8).setWidth(0);
    }

    /**
     * @return the jLabelAddress
     */
    public javax.swing.JLabel getjLabelAddress() {
        return jLabelAddress;
    }

    /**
     * @return the jLabelPhone
     */
    public javax.swing.JLabel getjLabelPhone() {
        return jLabelPhone;
    }


}
