/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ActivityReportController;
import dao.DeliveryOrderDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.DeliveryOrderModel;
import view.form.Form_ActivityReports;
import view.main.Home;
import view.system.SystemColor;

/**
 *
 * @author dandy
 */
public class Frame_CreateActivityReport extends javax.swing.JFrame {

    
    Form_ActivityReports formActivityReports;
    Home home;
    
    //Load Ticket List ComboBox
    DeliveryOrderDAO deliveryorderDAO;
    List<DeliveryOrderModel> deliveryOrders;
    
    /**
     * Creates new form JFCreateUser
     */
    public Frame_CreateActivityReport(Form_ActivityReports formActivityReports, Home home) {
        this.formActivityReports = formActivityReports;
        this.home = home;
        initComponents();
        
        
        //Load DO List ComboBox
        deliveryorderDAO = new DeliveryOrderDAO(home);
        deliveryOrders = deliveryorderDAO.getDeliveryOrders();
        if (deliveryOrders != null && !deliveryOrders.isEmpty()) {
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
            for (DeliveryOrderModel deliveryOrder : deliveryOrders) {
                comboBoxModel.addElement(String.valueOf(deliveryOrder.getId()));
            }
            jComboDOId.setModel(comboBoxModel);
        } else {
            jComboDOId.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Tidak ada DO yang tersedia.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        
        jLabelId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateStart = new com.raven.datechooser.DateChooser();
        jDateEnd = new com.raven.datechooser.DateChooser();
        jTimeEnd = new raven.datetime.component.time.TimePicker();
        jTimeStart = new raven.datetime.component.time.TimePicker();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelActionTaken = new javax.swing.JLabel();
        jLabelDOId = new javax.swing.JLabel();
        jComboDOId = new javax.swing.JComboBox<>();
        jLabelStartDate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextActionTaken = new javax.swing.JTextArea();
        jTextStartDate = new javax.swing.JTextField();
        jLabelEndDate = new javax.swing.JLabel();
        jTextEndDate = new javax.swing.JTextField();
        jLabelStartTime = new javax.swing.JLabel();
        jLabelEndTime = new javax.swing.JLabel();
        jFormattedStartTime = new javax.swing.JFormattedTextField();
        jFormattedEndTime = new javax.swing.JFormattedTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();

        jDateStart.setForeground(new java.awt.Color(143, 148, 251));
        jDateStart.setDateFormat("yyyy-MM-dd");
        jDateStart.setTextRefernce(jTextStartDate);

        jDateEnd.setForeground(new java.awt.Color(143, 148, 251));
        jDateEnd.setDateFormat("yyyy-MM-dd");
        jDateEnd.setTextRefernce(jTextEndDate);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 148, 251), 10));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setText("Create New Activity Report");

        jLabelActionTaken.setText("Action Taken");

        jLabelDOId.setText("DO ID");

        jComboDOId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelStartDate.setText("Start Date");

        jTextActionTaken.setColumns(20);
        jTextActionTaken.setRows(5);
        jScrollPane2.setViewportView(jTextActionTaken);

        jLabelEndDate.setText("End Date");

        jLabelStartTime.setText("Start Time");

        jLabelEndTime.setText("End Time");

        jFormattedStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedStartTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelActionTaken, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabelDOId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextEndDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextStartDate, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jLabelEndTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedStartTime)
                            .addComponent(jFormattedEndTime, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jComboDOId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboDOId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelDOId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelActionTaken)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStartDate)
                    .addComponent(jTextStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStartTime)
                    .addComponent(jFormattedStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndDate)
                    .addComponent(jTextEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEndTime)
                    .addComponent(jFormattedEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cancel.png"))); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/save.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelId.setText("jLabelId");

        jDesktopPane1.setLayer(jLabelTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonSave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelId, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelId)
                .addContainerGap(504, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSave))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (getjButtonSave().getText().equals("Save")){
            ActivityReportController activityReport = new ActivityReportController(formActivityReports, home);
            activityReport.saveActivityReport(this);
            activityReport.showActivityReports();
        }
        else {
            ActivityReportController activityReport = new ActivityReportController(formActivityReports, home);
            activityReport.updateActivityReport(this);
            activityReport.showActivityReports();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jFormattedStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedStartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedStartTimeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFCreateUser().setVisible(true);
//            }
//        });
//    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboDOId;
    private com.raven.datechooser.DateChooser jDateEnd;
    private com.raven.datechooser.DateChooser jDateStart;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFormattedTextField jFormattedEndTime;
    private javax.swing.JFormattedTextField jFormattedStartTime;
    private javax.swing.JLabel jLabelActionTaken;
    private javax.swing.JLabel jLabelDOId;
    private javax.swing.JLabel jLabelEndDate;
    private javax.swing.JLabel jLabelEndTime;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelStartDate;
    private javax.swing.JLabel jLabelStartTime;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextActionTaken;
    private javax.swing.JTextField jTextEndDate;
    private javax.swing.JTextField jTextStartDate;
    private raven.datetime.component.time.TimePicker jTimeEnd;
    private raven.datetime.component.time.TimePicker jTimeStart;
    // End of variables declaration//GEN-END:variables

    public void showTime() {
        getjTimeStart().set24HourView(true);
        getjTimeStart().setEditor(getjFormattedStartTime());
        getjTimeEnd().set24HourView(true);
        getjTimeEnd().setEditor(getjFormattedEndTime());
        getjTimeStart().setColor(SystemColor.MAIN_COLOR_1);
        getjTimeEnd().setColor(SystemColor.MAIN_COLOR_1);
    }

    /**
     * @return the jButtonCancel
     */
    public javax.swing.JButton getjButtonCancel() {
        return jButtonCancel;
    }

    /**
     * @return the jButtonSave
     */
    public javax.swing.JButton getjButtonSave() {
        return jButtonSave;
    }

    /**
     * @return the jComboDOId
     */
    public javax.swing.JComboBox<String> getjComboDOId() {
        return jComboDOId;
    }

    /**
     * @return the jDateEnd
     */
    public com.raven.datechooser.DateChooser getjDateEnd() {
        return jDateEnd;
    }

    /**
     * @return the jDateStart
     */
    public com.raven.datechooser.DateChooser getjDateStart() {
        return jDateStart;
    }

    /**
     * @return the jFormattedEndTime
     */
    public javax.swing.JFormattedTextField getjFormattedEndTime() {
        return jFormattedEndTime;
    }

    /**
     * @return the jFormattedStartTime
     */
    public javax.swing.JFormattedTextField getjFormattedStartTime() {
        return jFormattedStartTime;
    }

    /**
     * @return the jLabelId
     */
    public javax.swing.JLabel getjLabelId() {
        return jLabelId;
    }

    /**
     * @return the jTextActionTaken
     */
    public javax.swing.JTextArea getjTextActionTaken() {
        return jTextActionTaken;
    }

    /**
     * @return the jTextEndDate
     */
    public javax.swing.JTextField getjTextEndDate() {
        return jTextEndDate;
    }

    /**
     * @return the jTextStartDate
     */
    public javax.swing.JTextField getjTextStartDate() {
        return jTextStartDate;
    }

    /**
     * @return the jTimeEnd
     */
    public raven.datetime.component.time.TimePicker getjTimeEnd() {
        return jTimeEnd;
    }

    /**
     * @return the jTimeStart
     */
    public raven.datetime.component.time.TimePicker getjTimeStart() {
        return jTimeStart;
    }

    /**
     * @return the jLabelTitle
     */
    public javax.swing.JLabel getjLabelTitle() {
        return jLabelTitle;
    }
    
    
}
